/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.FeedController;
import java.awt.Rectangle;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Frederik
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        this.exchangerateInfo.setText("Press the button below to get the exchange to database");
        this.exchangerateButton.setText("Exchange rate");
        this.createFeedButton.setText("Create feed");
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exchangerateButton = new javax.swing.JButton();
        exchangerateInfo = new javax.swing.JLabel();
        createFeedButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exchangerateButton.setText("jButton1");
        exchangerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exchangerateButtonActionPerformed(evt);
            }
        });

        exchangerateInfo.setText("jLabel1");

        createFeedButton.setText("jButton1");
        createFeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createFeedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(exchangerateInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(exchangerateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 503, Short.MAX_VALUE)
                        .addComponent(createFeedButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(exchangerateInfo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exchangerateButton)
                    .addComponent(createFeedButton))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exchangerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exchangerateButtonActionPerformed
          try{
            FeedController fc = new FeedController();
            fc.insertExchangerateToDB();
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_exchangerateButtonActionPerformed

    private void createFeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createFeedButtonActionPerformed
       CreateFeedView cfv = new CreateFeedView();
       cfv.setBounds(50,50,650,650);
       cfv.setVisible(true);
       cfv.setResizable(false);
       cfv.setDefaultCloseOperation(HIDE_ON_CLOSE);
       
    }//GEN-LAST:event_createFeedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createFeedButton;
    private javax.swing.JButton exchangerateButton;
    private javax.swing.JLabel exchangerateInfo;
    // End of variables declaration//GEN-END:variables
}
